import Header from '@/components/organisms/Header'
import Provider from '@/config/provider'
import 'material-symbols'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import RouterInterceptor from '@/config/provider.config'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextTopLoader color="#0089CF" height={2} zIndex={10001} />
        <Toaster position="top-right" />
        <RouterInterceptor />
        <Provider>
          <div className="min-h-screen flex flex-col">
            <div className="flex-none">
              <Header />
            </div>
            <main className="flex-grow">{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  )
}
